In [1]:
import numpy as np

In [2]:
l = [1,2,3,4]

In [3]:
arr = np.array(l)

In [4]:
arr

array([1, 2, 3, 4])

In [5]:
type(arr)

numpy.ndarray

In [6]:
arr.shape

(4,)

In [7]:
arr.size

4

In [8]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
arr2d = np.array(arr2d,dtype='float')

In [10]:
arr2d

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [11]:
arr2d.astype('int')

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
arr2d

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [13]:
arr2d.astype('str')

array([['1.0', '2.0', '3.0'],
       ['4.0', '5.0', '6.0'],
       ['7.0', '8.0', '9.0']], dtype='<U32')

In [14]:
## Handling NaN and inf values
np.nan

nan

In [15]:
np.inf

inf

In [20]:
arr2d = arr2d.astype('float')

In [21]:
arr2d

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [22]:
arr2d[0][0] = np.nan
arr2d[1][2] = np.inf

In [23]:
arr2d

array([[nan,  2.,  3.],
       [ 4.,  5., inf],
       [ 7.,  8.,  9.]])

In [24]:
flag = np.isnan(arr2d) | np.isinf(arr2d)

In [25]:
flag

array([[ True, False, False],
       [False, False,  True],
       [False, False, False]])

In [27]:
arr2d[flag]

array([nan, inf])

In [28]:
arr2d[flag] = 0.0

In [29]:
arr2d

array([[0., 2., 3.],
       [4., 5., 0.],
       [7., 8., 9.]])

In [30]:
## Statistical Operators

mn = np.mean(arr2d)

In [31]:
mn

4.222222222222222

In [32]:
var = np.var(arr2d)

In [33]:
std = np.std(arr2d)

In [34]:
min1 = np.min(arr2d)
min1

0.0

In [36]:
max1 = np.max(arr2d)
max1

9.0

In [37]:
median = np.median(arr2d)

In [38]:
median

4.0

In [39]:
### shape,reshape,flatten,ravel

shape = np.shape(arr2d)

In [40]:
shape

(3, 3)

In [42]:
arr2d.reshape(1,9)

array([[0., 2., 3., 4., 5., 0., 7., 8., 9.]])

In [44]:
arr2d.reshape(1,9).ravel()

array([0., 2., 3., 4., 5., 0., 7., 8., 9.])

In [46]:
arr2d.reshape(1,9).flatten() ## ravel() and flatten doing same work of converting 2D array to 1D array 

array([0., 2., 3., 4., 5., 0., 7., 8., 9.])

In [47]:
### Sequence, Repeitition and Random numbers

np.arange(1,200,8)

array([  1,   9,  17,  25,  33,  41,  49,  57,  65,  73,  81,  89,  97,
       105, 113, 121, 129, 137, 145, 153, 161, 169, 177, 185, 193])

In [48]:
np.linspace(1,200,15)

array([  1.        ,  15.21428571,  29.42857143,  43.64285714,
        57.85714286,  72.07142857,  86.28571429, 100.5       ,
       114.71428571, 128.92857143, 143.14285714, 157.35714286,
       171.57142857, 185.78571429, 200.        ])

In [50]:
np.random.rand(3,2).astype('int')

array([[0, 0],
       [0, 0],
       [0, 0]])

In [52]:
np.random.randint(2,100,(3,4),dtype='int')

array([[60, 37, 19, 46],
       [60, 28, 49, 14],
       [67, 23, 88, 55]])

In [56]:
np.random.seed(1)
np.random.randint(2,100,(3,4),dtype='int')

array([[39, 14, 74, 11],
       [77,  7, 81, 66],
       [18,  3, 78, 73]])

In [57]:
np.unique(arr2d)

array([0., 2., 3., 4., 5., 7., 8., 9.])

In [58]:
np.unique(arr2d,return_counts=True)

(array([0., 2., 3., 4., 5., 7., 8., 9.]),
 array([2, 1, 1, 1, 1, 1, 1, 1], dtype=int64))

In [60]:
## Where() Function
arr = np.array([1,2,40,5,6,30,7,9])
index = np.where(arr>10)
index

(array([2, 5], dtype=int64),)

In [61]:
arr[arr>10]

array([40, 30])

In [62]:
arr>10

array([False, False,  True, False, False,  True, False, False])

In [64]:
### Saving Text Using Numpy

np.savetxt('data.csv',arr2d.astype('int'),delimiter=',',)

In [66]:
np.loadtxt('data.csv',delimiter=',')

array([[0., 2., 3.],
       [4., 5., 0.],
       [7., 8., 9.]])

In [69]:
np.savez('data1.npz',arr,arr2d)

In [72]:
np.load('data1.npz')

In [73]:
### Stacking and Concatenate
np.hstack([arr2d,arr2d])

array([[0., 2., 3., 0., 2., 3.],
       [4., 5., 0., 4., 5., 0.],
       [7., 8., 9., 7., 8., 9.]])

In [74]:
np.vstack([arr2d,arr2d])

array([[0., 2., 3.],
       [4., 5., 0.],
       [7., 8., 9.],
       [0., 2., 3.],
       [4., 5., 0.],
       [7., 8., 9.]])

In [75]:
arr.sort()

In [76]:
arr

array([ 1,  2,  5,  6,  7,  9, 30, 40])